swagger: "2.0"
info:
  description: "CPSV-AP Harvester API"
  version: "1.0.0"
  title: "Internal Harvester API"
  termsOfService: "https://ec.europa.eu/isa2/solutions/core-public-service-vocabulary-application-profile-cpsv-ap_en"
  contact:
    email: "emidio.stani@pwc.com"
  license:
    name: "Apache License"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "cpsv-ap.semic.eu"
basePath: "/cpsv-ap_harvester/intapi/v1"
tags:
- name: "Spreadsheet"
  description: "A spreasheet CPSV-AP 2.2.1 compliant."
schemes:
- "http"
paths:
  /importSpreadsheetFromURL:
    get:
      tags:
      - "Spreadsheet"
      summary: " Convert a spreadsheet from URL to JSON-LD"
      description: "Convert a spreadsheet CPSV-AP 2.2.1 compliant from URL to JSON-LD"
      operationId: "importSpreadsheetFromURL"
      produces:
      - "application/ld+json"
      parameters:
      - name: "spreadsheetURL"
        in: "query"
        description: "URL of the spreadsheet to provide"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PublicServiceDataset"
        400:
          description: "Invalid URL supplied"
        404:
          description: "Spreadsheet not found"
definitions:
  PublicServiceDataset:
    type: "array"
    items: 
      type: "string"
    xml:
      name: "PublicServiceDataset"
